### ISSUE TITLE
源码编译成X64时，编译出现错误	C2668

### ISSUE THREAD

**Issue by zhouxs1023** [mulab/mU#2]
编译出现下面的错误，不知道哪里有问题，编译成x86时，kernel是可以编译OK的，但是切换成X64就不行啦

错误	C2668	“mU::int_t::int_t”: 对重载函数的调用不明确	Kernel	d:\demo\mu\include\mu\var.h	256	

![123](https://user-images.githubusercontent.com/905931/189655868-e944f9a8-2db0-4bb1-bca5-6aa9a603ac36.PNG)

**Comment by lispc** [comment]
这都十几年老项目了。不维护了。你编译他有什么用吗？

**Comment by zhouxs1023** [comment]
看着还不错，就试图编译一下
